### ISSUE TITLE
如何从 application.yml 中读取请求地址

### ISSUE THREAD

**Issue by jay4q** [dromara/forest#152]
``` yml
forest:
  variables:
      base-url:http://abc.com/query
```

``` java
interface MyClient {
@Get(url = "{base-url}")
String query();
}
```

这样配置并运行后，无法获取base-url的值。有什么方法可以获取吗
