### ISSUE TITLE
模板表达式--变量引用名不支持特殊符号

### ISSUE THREAD

**Issue by iszhangsc** [dromara/forest#46]
*有一个这样的配置，读取就会报错*
```yml
forest:
  variables:
    xxx-search: http://baidu.com
```
版本：
```xml
<dependency>
    <groupId>com.dtflys.forest</groupId>
    <artifactId>forest-spring-boot-starter</artifactId>
    <version>1.5.2-BETA</version>
</dependency>
```
